- name: Ensure jmespath Python module is installed
  pip:
    name: jmespath
    state: present
    extra_args: "--no-cache-dir"
  delegate_to: localhost

- name: Convert user/password to a Bearer token
  ansible.builtin.set_fact:
    harbor_token: "{{ (harbor_username + ':' + harbor_password) | b64encode }}"

- name: Include tasks file
  ansible.builtin.include_tasks: harbor_tasks.yml
  loop: "{{ harbor_registries }}"
  no_log: true
